import styles from "./layout.module.css"
import { Inter } from "next/font/google";
import "@/globals.css";

const DMSans = Inter({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function LoginLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ru">
      <body className={ DMSans.className }>
        <div className={ styles.wrapper }>
          <div className={ styles.body }>
            { children }
          </div>
        </div>
      </body>
    </html >
  )
}
