import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import styles from "./layout.module.css";

import { Footer } from "./components/Footer/Footer";
import { Sidebar } from "./components/Sidebar/Sidebar";
import { Header } from "./components/ Header/Header";
import { SmallHeader } from "./components/SmallHeader/SmallHeader";



const DMSans = Inter({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={ DMSans.className }>
        <div className={ styles.wrapper }>
          <SmallHeader className={ styles["small-header"] } />
          <Header className={ styles.header } />
          <Sidebar className={ styles.sidebar } />
          <div className={ styles.body }>
            { children }
          </div>

          <Footer className={ styles.footer }></Footer>

        </div>
        <button className={ styles["sup-but"] }>dfsafdf</button>

      </body>

    </html>
  );
}
