import type { Metadata } from "next";
import styles from "./layout.module.css";




export const metadata: Metadata = {
    title: "Корзина",
    description: "Generated by create next app",
};

export default function CartLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className={ styles['cart-wrapper'] }>
            <div className={ styles['body'] }>
                { children }
            </div>
            <div className={ styles['accept'] }>sdfdf</div>
        </div>
    );
}
