import type { Metadata } from "next";
import styles from "./layout.module.css";




export const metadata: Metadata = {
    title: "Профиль",
    description: "Generated by create next app",
};

export default function ProfileLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div>
        </div>
    );
}
