import { Inter } from "next/font/google";
import { Header } from "../(site)/components/ Header/Header";
import { Footer } from "../(site)/components/Footer/Footer";
import { Sidebar } from "../(site)/components/Sidebar/Sidebar";
import styles from "./layout.module.css";
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
const DMSans = Inter({
  subsets: ['latin'],
  display: 'swap',
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ru">
      <body className={ DMSans.className }>
        <div className={ styles.wrapper }>
          <Header className={ styles.header }></Header>
          <div className={ styles.body }>
            { children }
          </div>
          <Footer className={ styles.footer }>asdffsad</Footer>
        </div>



      </body>
    </html>
  );
}
