import type { Metadata } from "next";
import styles from "./layout.module.css";
import { Sidebar } from "./components/Sidebar/Sidebar";




export const metadata: Metadata = {
    title: "Поиск",
    description: "Generated by create next app",
};

export default function SearchLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className={ styles.wrapper }>
            <Sidebar className={ styles.sidebar }>

            </Sidebar>
            <div className={ styles.body }>
                { children }
            </div>
        </div>
    );
}
