import { Inter } from "next/font/google";
import "@/globals.css";
import styles from "./layout.module.css";
import { Metadata } from "next";

import { SidebarProvider } from "./components/Sidebar/components/Context/sidebar.context";
import { SidebarTrigger } from "./components/Sidebar/components/SidebarTrigger/SidebarTrigger";
import { Sidebar } from "./components/Sidebar/Sidebar";
import { Navigator } from "./components/Navigator/Navigator";
import Link from "next/link";
import { NavigatorLink } from "./components/Navigator/components/NavigatorLink/NavigatorLink";



const DMSans = Inter({
    subsets: ['latin'],
    display: 'swap',
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function AdminLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ru">
            <body className={ DMSans.className } >

                <SidebarProvider>
                    <Sidebar></Sidebar>
                    <main className={ styles.main } >
                        <div className={ styles.nav }>
                            <SidebarTrigger></SidebarTrigger>
                            <Navigator />
                        </div>
                        <div className={ styles.body }>
                            { children }
                        </div>
                    </main>
                </SidebarProvider>

            </body>
        </html>
    )
}