blank_issues_enabled: false
contact_links:
  - name: Questions about the program / Вопросы по програме
    url: https://ntc.party/c/community-software/goodbyedpi/8
    about: Please ask and answer questions on forum / Пожалуйста, задавайте вопросы только на форуме
