import { Input } from "@/components/Input/Input";
import { Inter } from "next/font/google";
import "@/globals.css";
import styles from "./layout.module.css";
import { Metadata } from "next";


const DMSans = Inter({
    subsets: ['latin'],
    display: 'swap',
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function AdminLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {


    return (
        <html lang="ru">
            <body className={ DMSans.className }>
                <div className={ styles.wrapper }>

                    <div >
                        { children }
                    </div>
                </div>
            </body>
        </html>
    )
}